/*
===============================================================================
Project: E-commerce Customer Intelligence with SQL and Python
File: 08_customer_lifetime_value.sql
Purpose: Estimate customer lifetime value and customer value metrics
Dataset: Online Retail Dataset - UCI Machine Learning Repository
===============================================================================

Customer Lifetime Value, or CLV, estimates the value generated by a customer
over time.

This script calculates customer-level metrics such as:

- total revenue per customer;
- number of orders;
- average order value;
- purchase frequency;
- customer lifespan;
- average days between purchases;
- estimated customer lifetime value;
- customer value tiers.

===============================================================================
*/

-- =============================================================================
-- 1. Customer value base metrics
-- =============================================================================

WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date,
        ROUND(SUM(line_total), 2) AS order_revenue
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

customer_metrics AS (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS total_orders,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        ROUND(SUM(order_revenue), 2) AS total_revenue,
        ROUND(AVG(order_revenue), 2) AS average_order_value
    FROM customer_orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_orders,
    first_order_date,
    last_order_date,
    DATE_PART('day', last_order_date - first_order_date) AS customer_lifespan_days,
    total_revenue,
    average_order_value
FROM customer_metrics
ORDER BY total_revenue DESC;

-- =============================================================================
-- 2. Average days between purchases
-- =============================================================================

WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

ordered_purchases AS (
    SELECT
        customer_id,
        invoice_no,
        order_date,
        LAG(order_date) OVER (
            PARTITION BY customer_id
            ORDER BY order_date
        ) AS previous_order_date
    FROM customer_orders
),

purchase_intervals AS (
    SELECT
        customer_id,
        DATE_PART('day', order_date - previous_order_date) AS days_between_orders
    FROM ordered_purchases
    WHERE previous_order_date IS NOT NULL
)

SELECT
    customer_id,
    COUNT(*) AS repeat_purchase_intervals,
    ROUND(AVG(days_between_orders), 2) AS avg_days_between_orders,
    MIN(days_between_orders) AS min_days_between_orders,
    MAX(days_between_orders) AS max_days_between_orders
FROM purchase_intervals
GROUP BY customer_id
ORDER BY avg_days_between_orders;

-- =============================================================================
-- 3. Customer lifetime value estimation
-- =============================================================================
-- Simple historical CLV:
-- CLV = total revenue generated by the customer.
--
-- Estimated annualized CLV:
-- If customer_lifespan_days > 0:
-- annualized_clv = total_revenue / customer_lifespan_days * 365
--
-- For same-day customers, annualized CLV is set equal to total_revenue to avoid
-- division by zero.

WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date,
        ROUND(SUM(line_total), 2) AS order_revenue
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

customer_metrics AS (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS total_orders,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        DATE_PART('day', MAX(order_date) - MIN(order_date)) AS customer_lifespan_days,
        ROUND(SUM(order_revenue), 2) AS historical_clv,
        ROUND(AVG(order_revenue), 2) AS average_order_value
    FROM customer_orders
    GROUP BY customer_id
)

SELECT
    customer_id,
    total_orders,
    first_order_date,
    last_order_date,
    customer_lifespan_days,
    average_order_value,
    historical_clv,
    CASE
        WHEN customer_lifespan_days > 0
            THEN ROUND(historical_clv / customer_lifespan_days * 365, 2)
        ELSE historical_clv
    END AS estimated_annualized_clv
FROM customer_metrics
ORDER BY historical_clv DESC;

-- =============================================================================
-- 4. Customer value tiers
-- =============================================================================

WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date,
        ROUND(SUM(line_total), 2) AS order_revenue
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

customer_metrics AS (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS total_orders,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        DATE_PART('day', MAX(order_date) - MIN(order_date)) AS customer_lifespan_days,
        ROUND(SUM(order_revenue), 2) AS historical_clv,
        ROUND(AVG(order_revenue), 2) AS average_order_value
    FROM customer_orders
    GROUP BY customer_id
),

customer_clv AS (
    SELECT
        customer_id,
        total_orders,
        first_order_date,
        last_order_date,
        customer_lifespan_days,
        average_order_value,
        historical_clv,
        CASE
            WHEN customer_lifespan_days > 0
                THEN ROUND(historical_clv / customer_lifespan_days * 365, 2)
            ELSE historical_clv
        END AS estimated_annualized_clv
    FROM customer_metrics
),

tiered_customers AS (
    SELECT
        *,
        NTILE(5) OVER (ORDER BY historical_clv ASC) AS clv_score
    FROM customer_clv
)

SELECT
    customer_id,
    total_orders,
    customer_lifespan_days,
    average_order_value,
    historical_clv,
    estimated_annualized_clv,
    clv_score,
    CASE
        WHEN clv_score = 5 THEN 'Very High Value'
        WHEN clv_score = 4 THEN 'High Value'
        WHEN clv_score = 3 THEN 'Medium Value'
        WHEN clv_score = 2 THEN 'Low Value'
        ELSE 'Very Low Value'
    END AS customer_value_tier
FROM tiered_customers
ORDER BY historical_clv DESC;

-- =============================================================================
-- 5. Customer value tier summary
-- =============================================================================

WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date,
        ROUND(SUM(line_total), 2) AS order_revenue
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

customer_metrics AS (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS total_orders,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        DATE_PART('day', MAX(order_date) - MIN(order_date)) AS customer_lifespan_days,
        ROUND(SUM(order_revenue), 2) AS historical_clv,
        ROUND(AVG(order_revenue), 2) AS average_order_value
    FROM customer_orders
    GROUP BY customer_id
),

customer_clv AS (
    SELECT
        customer_id,
        total_orders,
        customer_lifespan_days,
        average_order_value,
        historical_clv,
        CASE
            WHEN customer_lifespan_days > 0
                THEN ROUND(historical_clv / customer_lifespan_days * 365, 2)
            ELSE historical_clv
        END AS estimated_annualized_clv
    FROM customer_metrics
),

tiered_customers AS (
    SELECT
        *,
        NTILE(5) OVER (ORDER BY historical_clv ASC) AS clv_score
    FROM customer_clv
),

customer_tiers AS (
    SELECT
        *,
        CASE
            WHEN clv_score = 5 THEN 'Very High Value'
            WHEN clv_score = 4 THEN 'High Value'
            WHEN clv_score = 3 THEN 'Medium Value'
            WHEN clv_score = 2 THEN 'Low Value'
            ELSE 'Very Low Value'
        END AS customer_value_tier
    FROM tiered_customers
)

SELECT
    customer_value_tier,
    COUNT(*) AS number_of_customers,
    ROUND(SUM(historical_clv), 2) AS total_historical_clv,
    ROUND(AVG(historical_clv), 2) AS avg_historical_clv,
    ROUND(AVG(estimated_annualized_clv), 2) AS avg_estimated_annualized_clv,
    ROUND(AVG(total_orders), 2) AS avg_orders_per_customer,
    ROUND(AVG(average_order_value), 2) AS avg_order_value
FROM customer_tiers
GROUP BY customer_value_tier
ORDER BY
    CASE
        WHEN customer_value_tier = 'Very High Value' THEN 1
        WHEN customer_value_tier = 'High Value' THEN 2
        WHEN customer_value_tier = 'Medium Value' THEN 3
        WHEN customer_value_tier = 'Low Value' THEN 4
        ELSE 5
    END;

-- =============================================================================
-- 6. CLV and RFM combined view
-- =============================================================================
-- This combines customer lifetime value with the RFM segments created in the
-- previous script.

SELECT
    r.customer_id,
    r.customer_segment,
    r.recency_days,
    r.frequency,
    r.monetary_value AS rfm_monetary_value,
    c.total_orders,
    c.customer_lifespan_days,
    c.average_order_value,
    c.historical_clv,
    c.estimated_annualized_clv,
    c.customer_value_tier
FROM vw_rfm_segments r
JOIN (
    WITH customer_orders AS (
        SELECT
            customer_id,
            invoice_no,
            MIN(invoice_date) AS order_date,
            ROUND(SUM(line_total), 2) AS order_revenue
        FROM vw_clean_transactions
        GROUP BY
            customer_id,
            invoice_no
    ),

    customer_metrics AS (
        SELECT
            customer_id,
            COUNT(DISTINCT invoice_no) AS total_orders,
            DATE_PART('day', MAX(order_date) - MIN(order_date)) AS customer_lifespan_days,
            ROUND(SUM(order_revenue), 2) AS historical_clv,
            ROUND(AVG(order_revenue), 2) AS average_order_value
        FROM customer_orders
        GROUP BY customer_id
    ),

    customer_clv AS (
        SELECT
            customer_id,
            total_orders,
            customer_lifespan_days,
            average_order_value,
            historical_clv,
            CASE
                WHEN customer_lifespan_days > 0
                    THEN ROUND(historical_clv / customer_lifespan_days * 365, 2)
                ELSE historical_clv
            END AS estimated_annualized_clv
        FROM customer_metrics
    ),

    tiered_customers AS (
        SELECT
            *,
            NTILE(5) OVER (ORDER BY historical_clv ASC) AS clv_score
        FROM customer_clv
    )

    SELECT
        customer_id,
        total_orders,
        customer_lifespan_days,
        average_order_value,
        historical_clv,
        estimated_annualized_clv,
        CASE
            WHEN clv_score = 5 THEN 'Very High Value'
            WHEN clv_score = 4 THEN 'High Value'
            WHEN clv_score = 3 THEN 'Medium Value'
            WHEN clv_score = 2 THEN 'Low Value'
            ELSE 'Very Low Value'
        END AS customer_value_tier
    FROM tiered_customers
) c
    ON r.customer_id = c.customer_id
ORDER BY c.historical_clv DESC;

-- =============================================================================
-- 7. Create reusable CLV view
-- =============================================================================

DROP VIEW IF EXISTS vw_customer_lifetime_value;

CREATE VIEW vw_customer_lifetime_value AS
WITH customer_orders AS (
    SELECT
        customer_id,
        invoice_no,
        MIN(invoice_date) AS order_date,
        ROUND(SUM(line_total), 2) AS order_revenue
    FROM vw_clean_transactions
    GROUP BY
        customer_id,
        invoice_no
),

customer_metrics AS (
    SELECT
        customer_id,
        COUNT(DISTINCT invoice_no) AS total_orders,
        MIN(order_date) AS first_order_date,
        MAX(order_date) AS last_order_date,
        DATE_PART('day', MAX(order_date) - MIN(order_date)) AS customer_lifespan_days,
        ROUND(SUM(order_revenue), 2) AS historical_clv,
        ROUND(AVG(order_revenue), 2) AS average_order_value
    FROM customer_orders
    GROUP BY customer_id
),

customer_clv AS (
    SELECT
        customer_id,
        total_orders,
        first_order_date,
        last_order_date,
        customer_lifespan_days,
        average_order_value,
        historical_clv,
        CASE
            WHEN customer_lifespan_days > 0
                THEN ROUND(historical_clv / customer_lifespan_days * 365, 2)
            ELSE historical_clv
        END AS estimated_annualized_clv
    FROM customer_metrics
),

tiered_customers AS (
    SELECT
        *,
        NTILE(5) OVER (ORDER BY historical_clv ASC) AS clv_score
    FROM customer_clv
)

SELECT
    customer_id,
    total_orders,
    first_order_date,
    last_order_date,
    customer_lifespan_days,
    average_order_value,
    historical_clv,
    estimated_annualized_clv,
    clv_score,
    CASE
        WHEN clv_score = 5 THEN 'Very High Value'
        WHEN clv_score = 4 THEN 'High Value'
        WHEN clv_score = 3 THEN 'Medium Value'
        WHEN clv_score = 2 THEN 'Low Value'
        ELSE 'Very Low Value'
    END AS customer_value_tier
FROM tiered_customers;

/*
===============================================================================
End of file: 08_customer_lifetime_value.sql
===============================================================================
*/
